export default {
  $schema: './node_modules/oxfmt/configuration_schema.json',
  arrowParens: 'always',
  bracketSpacing: true,
  ignorePatterns: [
    '**/.adonisjs/**',
    '**/.expo/**',
    '**/.turbo/**',
    '**/build/**',
    '**/bundle-audit/**',
    '**/database/schema.ts',
    '**/dist/**',
    '**/dist-*/**',
    '**/node_modules/**',
    '**/pnpm-lock.yaml',
    '**/public/assets/**',
    '**/tmp/**',
  ],
  printWidth: 100,
  semi: false,
  singleQuote: true,
  sortImports: {
    groups: [
      'side_effect',
      'builtin',
      'external',
      'internal',
      'parent',
      'sibling',
      'index',
      'type',
      'unknown',
    ],
    internalPattern: ['#', '@poc/'],
    newlinesBetween: true,
    order: 'asc',
  },
  trailingComma: 'all',
  useTabs: false,
}
